// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: apps/deploy/pb/rpc.proto

package deploy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	UpdateDeploy(ctx context.Context, in *CreateDeployRequest, opts ...grpc.CallOption) (*Deploy, error)
	QueryDeploy(ctx context.Context, in *QueryDeployRequest, opts ...grpc.CallOption) (*DeploySet, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) UpdateDeploy(ctx context.Context, in *CreateDeployRequest, opts ...grpc.CallOption) (*Deploy, error) {
	out := new(Deploy)
	err := c.cc.Invoke(ctx, "/infraboard.mcenter.deploy.RPC/UpdateDeploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) QueryDeploy(ctx context.Context, in *QueryDeployRequest, opts ...grpc.CallOption) (*DeploySet, error) {
	out := new(DeploySet)
	err := c.cc.Invoke(ctx, "/infraboard.mcenter.deploy.RPC/QueryDeploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	UpdateDeploy(context.Context, *CreateDeployRequest) (*Deploy, error)
	QueryDeploy(context.Context, *QueryDeployRequest) (*DeploySet, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) UpdateDeploy(context.Context, *CreateDeployRequest) (*Deploy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeploy not implemented")
}
func (UnimplementedRPCServer) QueryDeploy(context.Context, *QueryDeployRequest) (*DeploySet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeploy not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_UpdateDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).UpdateDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.mcenter.deploy.RPC/UpdateDeploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).UpdateDeploy(ctx, req.(*CreateDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_QueryDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).QueryDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.mcenter.deploy.RPC/QueryDeploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).QueryDeploy(ctx, req.(*QueryDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infraboard.mcenter.deploy.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDeploy",
			Handler:    _RPC_UpdateDeploy_Handler,
		},
		{
			MethodName: "QueryDeploy",
			Handler:    _RPC_QueryDeploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/deploy/pb/rpc.proto",
}
