// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: apps/setting/pb/setting.proto

package setting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SMS_PROVIDER int32

const (
	// 腾讯短信服务
	SMS_PROVIDER_TENCENT SMS_PROVIDER = 0
	// 阿里短信服务
	SMS_PROVIDER_ALI SMS_PROVIDER = 1
)

// Enum value maps for SMS_PROVIDER.
var (
	SMS_PROVIDER_name = map[int32]string{
		0: "TENCENT",
		1: "ALI",
	}
	SMS_PROVIDER_value = map[string]int32{
		"TENCENT": 0,
		"ALI":     1,
	}
)

func (x SMS_PROVIDER) Enum() *SMS_PROVIDER {
	p := new(SMS_PROVIDER)
	*p = x
	return p
}

func (x SMS_PROVIDER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SMS_PROVIDER) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_setting_pb_setting_proto_enumTypes[0].Descriptor()
}

func (SMS_PROVIDER) Type() protoreflect.EnumType {
	return &file_apps_setting_pb_setting_proto_enumTypes[0]
}

func (x SMS_PROVIDER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SMS_PROVIDER.Descriptor instead.
func (SMS_PROVIDER) EnumDescriptor() ([]byte, []int) {
	return file_apps_setting_pb_setting_proto_rawDescGZIP(), []int{0}
}

type NOTIFY_TYPE int32

const (
	// 邮件通知
	NOTIFY_TYPE_MAIL NOTIFY_TYPE = 0
	// 短信通知
	NOTIFY_TYPE_SMS NOTIFY_TYPE = 1
)

// Enum value maps for NOTIFY_TYPE.
var (
	NOTIFY_TYPE_name = map[int32]string{
		0: "MAIL",
		1: "SMS",
	}
	NOTIFY_TYPE_value = map[string]int32{
		"MAIL": 0,
		"SMS":  1,
	}
)

func (x NOTIFY_TYPE) Enum() *NOTIFY_TYPE {
	p := new(NOTIFY_TYPE)
	*p = x
	return p
}

func (x NOTIFY_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NOTIFY_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_setting_pb_setting_proto_enumTypes[1].Descriptor()
}

func (NOTIFY_TYPE) Type() protoreflect.EnumType {
	return &file_apps_setting_pb_setting_proto_enumTypes[1]
}

func (x NOTIFY_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NOTIFY_TYPE.Descriptor instead.
func (NOTIFY_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_apps_setting_pb_setting_proto_rawDescGZIP(), []int{1}
}

var File_apps_setting_pb_setting_proto protoreflect.FileDescriptor

var file_apps_setting_pb_setting_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x70,
	0x62, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1a, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2a, 0x24, 0x0a, 0x0c, 0x53,
	0x4d, 0x53, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x12, 0x0b, 0x0a, 0x07, 0x54,
	0x45, 0x4e, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x49, 0x10,
	0x01, 0x2a, 0x20, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x4d,
	0x53, 0x10, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6d, 0x63, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_setting_pb_setting_proto_rawDescOnce sync.Once
	file_apps_setting_pb_setting_proto_rawDescData = file_apps_setting_pb_setting_proto_rawDesc
)

func file_apps_setting_pb_setting_proto_rawDescGZIP() []byte {
	file_apps_setting_pb_setting_proto_rawDescOnce.Do(func() {
		file_apps_setting_pb_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_setting_pb_setting_proto_rawDescData)
	})
	return file_apps_setting_pb_setting_proto_rawDescData
}

var file_apps_setting_pb_setting_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apps_setting_pb_setting_proto_goTypes = []interface{}{
	(SMS_PROVIDER)(0), // 0: infraboard.mcenter.setting.SMS_PROVIDER
	(NOTIFY_TYPE)(0),  // 1: infraboard.mcenter.setting.NOTIFY_TYPE
}
var file_apps_setting_pb_setting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_setting_pb_setting_proto_init() }
func file_apps_setting_pb_setting_proto_init() {
	if File_apps_setting_pb_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_setting_pb_setting_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_setting_pb_setting_proto_goTypes,
		DependencyIndexes: file_apps_setting_pb_setting_proto_depIdxs,
		EnumInfos:         file_apps_setting_pb_setting_proto_enumTypes,
	}.Build()
	File_apps_setting_pb_setting_proto = out.File
	file_apps_setting_pb_setting_proto_rawDesc = nil
	file_apps_setting_pb_setting_proto_goTypes = nil
	file_apps_setting_pb_setting_proto_depIdxs = nil
}
