[app]
name = "mcenter"
key  = "this is your app key"

[http]
host = "127.0.0.1"
port = 8010

[grpc]
host = "127.0.0.1"
port = 18010

[mongodb]
endpoints = ["127.0.0.1:27017"]
database = "mcenter"

[log]
level = "debug"

[log.file]
enable = true

[jaeger]
enable = false